### ISSUE TITLE
🗣 Problem Statement Review

### ISSUE THREAD

**Issue by keshavd** [keshavd/cas741#1]
Hi @smiths!

I've prepared a problem statement in the repo. I would appreciate any constructive feedback. It's a bit long but I believe the additional information helps clarify the problem. 

I am expecting to rewrite this more formally in the near future.

https://github.com/keshavd/cas741/blob/master/docs/problem_statement/problem_statement.pdf

Cheers,
Keshav

**Comment by smiths** [comment]
The background information in the problem statement is great, but I still don't quite know exactly what your program will do.  Please include a statement about the input to your program and its output.  This should make it clear.

**Comment by smiths** [comment]
I also pushed a version of your problem statement that has a few comments on your LaTeX code.

**Comment by smiths** [comment]
@keshavd, can  you please revise your problem statement so that we can close this issue?

**Comment by smiths** [comment]
@keshavd, you need to revise your problem statement before we can close this issue.  It shouldn't be much work to do the revision, especially after your presentation the other day.  If you have any questions, please let me know.

**Comment by keshavd** [comment]
@smiths I have made the required revisions

**Comment by smiths** [comment]
Looks good.  (A little on the long side, but that isn't a big deal.)  Your problem statement is approved.
